lib: [
  "/home/selfofly/Documents/Functional Programming/reasonTrie/_esy/default/store/b/esybuild-dd43e494/install/default/lib/reasonTrie/META"
  "/home/selfofly/Documents/Functional Programming/reasonTrie/_esy/default/store/b/esybuild-dd43e494/install/default/lib/reasonTrie/dune-package"
  "/home/selfofly/Documents/Functional Programming/reasonTrie/_esy/default/store/b/esybuild-dd43e494/install/default/lib/reasonTrie/opam"
]
bin: [
  "/home/selfofly/Documents/Functional Programming/reasonTrie/_esy/default/store/b/esybuild-dd43e494/install/default/bin/app"
]
doc: [
  "/home/selfofly/Documents/Functional Programming/reasonTrie/_esy/default/store/b/esybuild-dd43e494/install/default/doc/reasonTrie/LICENSE"
  "/home/selfofly/Documents/Functional Programming/reasonTrie/_esy/default/store/b/esybuild-dd43e494/install/default/doc/reasonTrie/README.md"
]
